defaults:
  - _self_
  - cameras: basler
  - lights: none
  - strategies: light_sequence # null for no particular collection modes
  - postprocessings: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  save_dir: "${oc.env:ROOT}/results/grabbed"
  log_file: "${oc.env:ROOT}/results/log.txt"

mode:
  val: manual
  valid_options:
    - manual
    - light_sequence
  one_cam_at_time: False
  in_ram: False

save:
  raw: false
  postprocessed: true

test_lights: False

camera_ids: null
