defaults:
  - _self_
  - cameras: basler
  - lights: gardasoft
  - strategies: light_sequence # null for no particular collection modes
  - postprocessings: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  save_dir: "${oc.env:ROOT}/data/grabbed"
  log_file: "${oc.env:ROOT}/data/logs/log.txt"

mode:
  val: manual
  valid_options:
    - manual
    - light_sequence

save:
  raw: false
  postprocessed: true
