defaults:
  - _self_
  - cameras: none
  - lights: gardasoft
  - strategies: light_sequence # null for no particular collection modes
  - postprocessings: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  save_dir: "${oc.env:ROOT}/results/grabbed"
  log_file: "${oc.env:ROOT}/results/log.txt"

test_lights: True
